spring.application.name=SMMDS

spring.datasource.url=jdbc:postgresql://dpg-d7olcjvavr4c73caa47g-a.oregon-postgres.render.com/projeto_integrador_oize
spring.datasource.username=projeto_integrador_oize_user
spring.datasource.password=UCcQnZ94eh0y2laaKmIregEwwMnCF4VZ
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver

springdoc.swagger-ui.path=/aula/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
